# This container is for a complete dev and test environment setup that can be shared
# among developers on the Zagg-Imaginea project.

# =====================================================================
# Build the stellar-dev-base image using the Dockerfile-dev-base
# script using the following command -
#
# docker build -t zagg-dev-base -f Dockerfile-dev-base .
# docker build -t zagg-dev -f Dockerfile-dev
# =====================================================================
FROM zagg-dev-base

MAINTAINER Srikumar Subramanian <srikumarks@gmail.com>

# This is from Dockerfile in https://github.com/stellar/docker-base
# The "install" script in that repo is moved over here as "preinstall"
ENV CONFD_VERSION 0.15.0
VOLUME /logs
VOLUME /cores
ADD preinstall /
RUN /preinstall

ENV STELLAR_CORE_VERSION 11.0.0-901-236f8315
ENV HORIZON_VERSION 0.17.5

EXPOSE 5432
EXPOSE 8000
EXPOSE 11625
EXPOSE 11626

ADD dependencies /
RUN ["chmod", "+x", "dependencies"]
RUN /dependencies

# ================== SOURCE CODE BUILD ==================
# Use --build-arg repo=https://github.com/stellar/stellar-core.git
# to change the repo that this container is expected to build.
# =======================================================
ARG repo=https://github.com/stellar/stellar-core.git

RUN mkdir -p /src \
        && cd /src \
        && git clone $repo repo \
        && cd repo \
        && git submodule init \
        && git submodule update \
        && ./autogen.sh \
        && ./configure \
        && make \
        && echo "SKIPPING make check ..." \
        && make install

# Needed for running the container
RUN apt-get install -y rsync

# =================== REST OF SETUP ======================

ADD install /
RUN ["chmod", "+x", "install"]
RUN /install

RUN ["mkdir", "-p", "/opt/stellar"]
RUN ["touch", "/opt/stellar/.docker-ephemeral"]

RUN useradd --uid 10011001 --home-dir /home/stellar --no-log-init stellar \
    && mkdir -p /home/stellar \
    && chown -R stellar:stellar /home/stellar

RUN ["ln", "-s", "/opt/stellar", "/stellar"]
RUN ["ln", "-s", "/opt/stellar/core/etc/stellar-core.cfg", "/stellar-core.cfg"]
RUN ["ln", "-s", "/opt/stellar/horizon/etc/horizon.env", "/horizon.env"]
ADD common /opt/stellar-default/common
ADD pubnet /opt/stellar-default/pubnet
ADD testnet /opt/stellar-default/testnet
ADD standalone /opt/stellar-default/standalone

# We run git daemon on the downloaded repository, so that you 
# can check out the code from outside the container and commit
# to it.
#
# git clone git://$ZaggIPAddress/repo
#
# where ZaggIPAddress is obtained using -
# ZaggIPAddress=`docker inspect --format='{{.NetworkSettings.IPAddress}}' zagg`
EXPOSE 9418

ADD start /
RUN ["chmod", "+x", "start"]

ENTRYPOINT ["/init", "--", "/start" ]
